name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - hex # 或你使用的默认分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ./

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18" # 设置 Node.js 版本

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: ./

      - name: Install Hexo CLI
        run: npm install -g hexo-cli
        working-directory: ./

      - name: Generate static pages
        run: hexo generate
        working-directory: ./

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./public
          external_repository: yaodao0520/yaodao0520.github.io # 更改为你的 GitHub Pages 仓库，username 是你的用户名
          publish_branch: main # GitHub Pages 分支
